# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-17 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeestatsApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', validators=[oauth2_provider.validators.validate_uris])),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], max_length=32)),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to=b'appimages', verbose_name='application logo')),
                ('agree', models.BooleanField(verbose_name='API usage agreement')),
                ('website', models.URLField(help_text='A website where interested users can find more information aboutthe application and where to download it for their own use.', verbose_name='application website')),
                ('description', models.TextField(max_length=8192)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caffeine_oauth2_coffeestatsapplication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Coffeestats OAuth2 application',
                'verbose_name_plural': 'Coffeestats OAuth2 applications',
            },
        ),
    ]
