# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caffeine_oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeestatsapplication',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved by coffeestats team'),
        ),
        migrations.AddField(
            model_name='coffeestatsapplication',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coffeestatsapplication',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time of approval by the coffeestats team'),
        ),
    ]
