# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine_oauth2', '0002_auto_20160929_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeestatsapplication',
            options={
                'permissions': (('can_approve', 'Can approve applications'),),
                'verbose_name': 'Coffeestats OAuth2 application',
                'verbose_name_plural': 'Coffeestats OAuth2 applications'
            },
        ),
    ]
