# Generated by Django 2.2.28 on 2024-05-13 16:23

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caffeine_oauth2", "0004_auto_20181006_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeestatsapplication",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="coffeestatsapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, help_text="Allowed Post Logout URIs list, space separated"
            ),
        ),
        migrations.AlterField(
            model_name="coffeestatsapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="coffeestatsapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Hashed on Save. Copy it now if this is a new secret.",
                max_length=255,
            ),
        ),
    ]
