language: python
sudo: true
python:
  - "3.5"
services:
  - docker
install:
  - "./generate-env.sh"
  - "docker-compose build"
  - pip install coveralls
script:
  - "docker-compose up -d db && sleep 5"
  - "docker-compose up -d && sleep 5"
  - "docker-compose exec app coverage run --branch manage.py test -v 1"
after_success:
  - "cd coffeestats ; coverage combine .coverage ; coveralls"
