language: python
sudo: true
python:
  - "3.6"
services:
  - docker
install:
  - "./generate-env.sh"
  - "docker-compose build"
  - pip install coveralls
script:
  - "docker-compose up -d && sleep 10 && docker-compose exec app coverage run --branch manage.py test -v 1"
after_success:
  coveralls --data-file coffeestats/.coverage
