version: "3"
services:
  db:
    build:
      context: docker/db
    restart: always
    env_file: .env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "15432:5432"
  app:
    build:
      context: .
      dockerfile: coffeestats/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - "./coffeestats:/srv/coffeestats"

volumes:
  pg_data:
