[project]
name = "coffeestats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bcrypt==4.0.1",
    "django-absolute>=0.3",
    "django-debug-toolbar>=4.4.6",
    "django-extensions>=3.2.3",
    "django-model-utils>=4.5.1",
    "django-registration>=3.4",
    "django<5",
    "djangorestframework>=3.15.2",
    "drf-nested-routers>=0.94.1",
    "passlib~=1.7.4",
    "pillow>=10.4.0",
    "psycopg2-binary~=2.9.9",
]

[tool.uv]
dev-dependencies = [
    "coverage>=7.6.9",
    "ruff>=0.6.3",
    "selenium>=4.24.0",
]
