#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username="${POSTGRES_USER}" --dbname="${POSTGRES_DB}" <<EOSQL
    CREATE USER ${COFFEESTATS_PGSQL_USER} PASSWORD '${COFFEESTATS_PGSQL_PASSWORD}' CREATEDB;
    CREATE DATABASE ${COFFEESTATS_PGSQL_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${COFFEESTATS_PGSQL_DATABASE} TO ${COFFEESTATS_PGSQL_USER};
EOSQL
