# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine', '0003_auto_20150219_0031'),
        ('caffeine', '0003_auto_20160116_1951'),
    ]

    operations = [
    ]
